src/store/cache/analytics/hooks.ts
Zero'd out metrics break other graphs
=> Add safety checks

src/components/AppBar/AppBar.module.css, src/components/AppBar/AppBar.tsx, src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.tsx, src/services/Audius/AudiusClient.ts, src/services/Audius/setup.ts, src/store/cache/discoveryProvider/hooks.ts, src/store/index.ts
Tested the following flows 
(against prod)
```
no metamask installed
metamask installed, locked
metamask installed, unlocked, not connected
metamask installed, unlocked, connected
switch metamask accounts
metamask installed, unlocked, wrong config
metamask installed, unlocked, switch to right config
```
=> Fix metamask auth flow

src/services/Audius/setup.ts
Attempt #2 at fixing infinite reload loop. Very hard to repro, but I think it has to do with the timing of page load & registering callbacks on window.ethereum vs. when metamask manages to inject into page.
=> Fix infinite reload

src/components/NewProposalModal/NewProposalModal.tsx, src/store/cache/proposals/hooks.ts, src/store/cache/proposals/slice.ts
Fix typo and bugfix to return resolved proposals in reverse chronological order
=> Typo and resolved proposal order bugfix

src/services/3box/index.ts
3box images weren't loading because the query param changed from wallet to address
=> Fix 3box images

package-lock.json, package.json, src/components/TopAddressesTable/TopAddressesTable.tsx, src/components/TransactionStatus/TransactionStatus.tsx, src/containers/Home/Home.tsx, src/store/actions/cancelTransaction.ts
Cards:
https://trello.com/c/Yo8g7gAB/1739-fix-modal-scroll-wonkiness-in-protocol-dashboard
https://trello.com/c/C6b8vQOk/390-sorting-of-vote-weight-is-incorrect-based-on-total-stake-vs-active-stake
https://trello.com/c/SP8iEbSM/385-double-modal-causes-modal-state-to-get-wonky-when-undelegating
https://trello.com/c/chXhLlnj/387-copy-tweak-change-250k-to-1m
=> Minor bugfixes

src/containers/User/User.tsx
Display the active delegation on the user page in the top right instead of the current delegation. 
Note: Active delegation is current delegation minus pending undelegate request amount.
=> Display active delegation

src/components/ConfirmTransactionModal/ConfirmTransactionModal.tsx, src/components/ManageService/ManageService.module.css, src/components/ManageService/ManageService.tsx, src/components/ProposalHero/ProposalHero.tsx, src/components/TransactionStatus/TransactionStatus.tsx, src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserInfo.tsx, src/components/UserStakedStat/UserStakedStat.module.css, src/components/UserStakedStat/UserStakedStat.tsx, src/containers/User/User.tsx, src/store/cache/protocol/hooks.ts, src/store/cache/timeline/hooks.ts
Cards:
https://trello.com/c/qqj602u7/378-would-be-good-to-add-a-global-loading-state-to-user-profile-pages-they-appear-blank-while-theyre-loading-in
https://trello.com/c/AD26fzhe/377-would-be-good-to-have-a-loading-state-for-est-time-remaining-on-governance-proposals-when-you-come-in-on-page-load-it-shows-0-fo
https://trello.com/c/GMUjUr9M/389-actions-cannot-be-taken-until-pending-transactions-complete-text-shows-for-too-many-types-of-errors
=> Loading states

package-lock.json, package.json, src/services/Audius/delegate.ts, src/store/actions/cancelTransaction.ts
Update the libs method names to match the contract call 
* Note: 
this relies on the libs being updated in this pr - https://github.com/AudiusProject/audius-protocol/pull/1124. 
It also needs a libs version bump and the libs in package.json to be updated/
Link libs locally (Note that there are libs changes) and canceled remove delegator and cancel undelegate stake
=> Update cancel contract method names

src/components/Timeline/Timeline.tsx, src/components/Timeline/TimelineEvent.module.css, src/components/Timeline/TimelineEvent.tsx, src/containers/User/User.tsx, src/services/Audius/delegate.ts, src/services/Audius/serviceProviderClient.ts, src/store/cache/timeline/hooks.ts
This should take care of all the spec'd events for now.
Adds:
- Undelegate request/eval/cancel from both SP + delegator perspective
- SP delegation request cancel
Also cleaned up some of yesterday's code a tiny bit.
=> Add more timeline events

src/components/DelegatorsModal/DelegatorsModal.module.css, src/components/DelegatorsModal/DelegatorsModal.tsx, src/components/Modal/Modal.tsx, src/components/ModalTable/ModalTable.tsx, src/store/cache/user/hooks.ts
https://trello.com/c/aM2joTVR/393-delegators-sort-order-is-not-sorted-by-delegated-amt-https-dashboardaudiusorg-services-operator-0x8c860adb28ca8a33db5571536bfcf7
https://trello.com/c/qftVpR65/394-delegators-modal-doesnt-show-delegated-value-and-probably-doesnt-sort-as-well
=> Fix sort ordering and info in delegators modal

src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserInfo.tsx, src/containers/User/User.tsx
=> Delegate view fix

src/store/cache/user/graph/formatter.ts
=> Remove unused vars for build

src/components/Delegate/Delegate.tsx, src/components/ManageService/ManageService.tsx, src/store/account/hooks.ts
Checks if the decrease delegation should be disabled. 
Closes AUD-200
=> Disable decrease delegation if already pending

src/store/cache/analytics/hooks.ts
This reverts commit b1dc2407843d0a1432295add42a3d93252a0cbb2.
=> Revert "Halt analytics while discovery nodes are unhealthy (#59)"

src/components/Delegate/Delegate.module.css, src/components/Delegate/Delegate.tsx, src/components/Tooltip/Tooltip.tsx
Disabled increase/decrease delegation if there is a pending claim for the user. 
Closes AUD-278
=> Jowlee disable delegate claim

package-lock.json, package.json
=> Bump audius libs with event name fix

package.json, src/hooks/useRerouteLegacy.ts
This will allow rendering of the dapp using the cid or ipns.
=> Relative routing for ipns to work

src/components/AppBar/AppBar.tsx, src/components/Delegate/Delegate.tsx, src/components/DelegatesModal/DelegatesModal.tsx, src/components/DelegatesTable/DelegatesTable.tsx, src/components/DelegationStatsChip/DelegationStatsChip.tsx, src/components/DelegatorsModal/DelegatorsModal.tsx, src/components/DelegatorsTable/DelegatorsTable.tsx, src/components/DisplayAudio/DisplayAudio.module.css, src/components/DisplayAudio/DisplayAudio.tsx, src/components/DisplayAudio/index.tsx, src/components/ProposalHero/ProposalHero.tsx, src/components/StakingStat/StakingStat.tsx, src/components/StatsChip/StatsChip.tsx, src/components/Timeline/TimelineEvent.tsx, src/components/Tooltip/Tooltip.tsx, src/components/TopAddressesTable/TopAddressesTable.tsx, src/components/TopOperatorsTable/TopOperatorsTable.tsx, src/components/TotalStakedStat/TotalStakedStat.tsx, src/components/UpdateDelegationModal/UpdateDelegationModal.tsx, src/components/UpdateStakeModal/UpdateStakeModal.tsx, src/components/UserStakedStat/UserStakedStat.tsx, src/components/ValueSlider/ValueSlider.tsx, src/components/VoteMeter/VoteMeter.tsx, src/components/VotesTable/VotesTable.tsx, src/utils/format.ts
* Replaces all instances of displaying audio w/ a component
* On click audio value, copies the wei amount to clipboard
Closes AUD-313
=> Add click to copy on audio

src/components/EstimatedAnnualStat/EstimatedAnnualStat.tsx, src/components/EstimatedAnnualStat/index.tsx, src/components/EstimatedWeeklyStat/EstimatedWeeklyStat.tsx, src/components/EstimatedWeeklyStat/index.tsx, src/components/MyEstimatedRewards/MyEstimatedRewards.module.css, src/components/MyEstimatedRewards/MyEstimatedRewards.tsx, src/components/MyEstimatedRewards/index.tsx, src/components/RewardStat/RewardStat.module.css, src/components/RewardStat/RewardStat.tsx, src/components/RewardStat/index.tsx, src/components/StatsChip/StatsChip.module.css, src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserInfo.tsx, src/containers/Home/Home.module.css, src/containers/Home/Home.tsx, src/hooks/useRewardRate.ts, src/services/Audius/claim/claim.ts, src/services/Audius/helpers.ts, src/services/Audius/setup.ts, src/store/cache/claims/hooks.ts, src/store/cache/claims/slice.ts, src/store/cache/rewards/helpers.ts, src/store/cache/rewards/hooks.ts, src/store/cache/rewards/slice.ts, src/store/index.ts, src/store/types.ts
Adds estimated rewards
Closes AUD-307
Design: https://www.figma.com/file/5fHG3aUYmqaiyHzUJpXKeo/Misc-Features?node-id=1226%3A15510
=> Add estimated reward

src/components/Proposal/Proposal.module.css, src/components/Proposal/Proposal.tsx, src/components/Timeline/TimelineEvent.tsx, src/components/Timeline/TimelineModal.tsx
=> Disable click row on timeline modal

package-lock.json, package.json
Update libs to include this PR for more accurate gas estimates
https://github.com/AudiusProject/audius-protocol/pull/1368
Fixes AUD-280
=> Update libs with gas estimate

package-lock.json, package.json, src/components/NewProposalModal/NewProposalModal.tsx, src/components/Timeline/TimelineEvent.tsx
Updates stems - this changes the modal allow scroll prop from overflow:scroll to auto
Adds scroll to the proposal modal 
Fixes AUD-498
Also fixes wallet addresses in the timeline not being shortened.
=> Update stems and fix addr in timeline

src/components/AppBar/AppBar.module.css, src/components/AppBar/AppBar.tsx, src/components/DelegationStatsChip/DelegationStatsChip.tsx, src/components/ManageService/ManageService.module.css, src/components/StakingStat/StakingStat.tsx, src/components/Timeline/TimelineEventMobile.module.css, src/components/Tooltip/Tooltip.module.css, src/components/UserImage/UserImage.tsx, src/components/UserStakedStat/UserStakedStat.tsx, src/containers/Home/Home.module.css, src/containers/User/User.tsx, src/containers/User/UserMobile.module.css
Updates the App bar to include staked as well as tokens
Fixes AUD-322
Fixed mobile display issues w/ text inline on timeline events.
=> Update app bar and mobile spacing

.circleci/config.yml
dashboard-cid.audius.org
dashboard-staging-cid.audius.org 
This PR mirrors https://github.com/AudiusProject/audius-client/pull/400
=> Publish CIDs

src/store/cache/analytics/hooks.ts, src/store/cache/music/hooks.ts, src/utils/fetch.ts
Bug exposed due to mumbaudius being offline
=> Fix bug in dp selection

src/utils/fetch.ts
This doesn't work on staging and I don't think we need it (?)
wdyt. should we build something else?
=> Remove api.audius.co filter

src/services/Audius/setup.ts, src/store/cache/analytics/hooks.ts, src/store/cache/music/hooks.ts, src/utils/fetch.ts
So that we know the selected discovery node is healthy
=> Use discovery node selection from libs

.circleci/config.yml
build-prod worked, but not staging because I added the the resource size to the wrong job.
=> Updated wrong resource size

package-lock.json, package.json, src/components/ServiceTable/ServiceTable.module.css, src/components/ServiceTable/ServiceTable.tsx, src/services/Audius/AudiusClient.ts, src/services/Audius/helpers.ts, src/store/cache/contentNode/hooks.ts, src/store/cache/discoveryProvider/hooks.ts, src/types.ts
Adds national flags next to node operators. Pulls the countryCode from each node's health-check endpoint
=> [AUD-73] Add flags for node operators

package-lock.json, package.json
Need v1.2.89 on protocol dashboard to test new service features on stage
=> Bump libs to v1.2.90

src/services/SelfId/SelfId.ts
Improves self.id image fallback, fixing missing images for stakers in prod:
=> [C-671] Fix self.id image fallback

.circleci/config.yml, package-lock.json, package.json
It works:
https://app.circleci.com/pipelines/github/AudiusProject/protocol-dashboard/490/workflows/877b4066-7b51-4915-84a1-5c491b9c981b/jobs/1892
https://dashboard.staging.audius.org
=> [INF-308] Move dashboard.staging.audius.org to armada
