AudiusProject/protocol-dashboard

- src/components/TransactionStatus/TransactionStatus.tsx
- src/store/cache/protocol/hooks.ts
Tried to update SP deployer cut and I ran into two bugs
1. The time until the lockup ended had the wrong units, it kept showing like 28 minutes and kept resetting itself to 28 every so often when it should have been in days. That's because the useTimeRemaining hook returns seconds, but all the functions in format.ts require ms, so I multiplied by 1000 while setting timeRemaining. I tried to check all uses of timeRemaining (like useProposalTimeRemaining in Proposal.tsx and that calls a function that requires ms too, but I may have missed something.
2. After i fixed 1, I noticed the time period was off. It was 18 days instead of around 9 days. The reason for that I believe is useTimeRemaining takes in `block`, `period` and calculates `targetBlock`. However, the `block` being passed in is …
> Fix for incorrect expiry time

- src/services/Audius/setup.ts
https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange
I believe this is super buggy and with our existing event listener it's done the right way. Sometimes there's some race condition here.
Also tiny fix to prevent showing a button when metamask is misconfigured 
TESTED=Locally against prod
> Fix metamask infinite reload bug

- src/store/cache/analytics/hooks.ts
Fixes charts where the first item in the dataset is not of max length.
The datasets we get here are (dumbed down)
1. [{ts: 10, count: 10}, {ts: 9, count: 10}]
2. [{ts: 10, count: 5}, {ts: 9, count: 5}, {ts: 8, count: 4}]
The joined dataset should be
[{ts: 10, count: 15}, {ts: 9, count: 15}, {ts: 8, count: 4}]
If we "join" these datasets with #2 first, everything's cool, but if we join with #1 first, we end up not getting all the timestamps
> Fix charts

- src/components/LineChart/LineChart.tsx
- src/store/cache/analytics/hooks.ts
- src/utils/performWithFallback.ts
This PR contains a few changes:
- Consumes new `trailing` endpoints for API + App Name
- Optionally rounds to nearest day for time series data, so the final day has complete data
- Optionally removes leading day in Line charts
- Introduces fallback mechanism to support legacy endpoints
Also edited some existing endpoints to properly throw if `!res.ok`. 
Tested by running against local DP w/ snapshotted prod, hardcoding values as necessary
> Consume optimized endpoints

- src/components/ProposalHero/ProposalHero.tsx
The time remaining in the Governance hero was in the format hh:mm:ss, but it didn't account for times of multiple days. Switched that to consume the `getHumanReadableTime` function which is used in other places that displays the two largest units of time remaining.
> Move proposalHero from getTime to getHumanReadableTime

- package-lock.json
- package.json
- src/components/DelegatesTable/DelegatesTable.tsx
- src/components/DelegatorsTable/DelegatorsTable.tsx
- src/components/ProposalHero/ProposalHero.tsx
- src/components/Proposals/Proposals.tsx
- src/components/TopAddressesTable/TopAddressesTable.tsx
- src/containers/User/User.tsx
- src/services/Audius/delegate.ts
- src/services/Audius/wrappers.ts
- src/store/cache/user/hooks.ts
- src/types.ts
- src/utils/activeStake.ts
Trello card - https://trello.com/c/XaUCCuvG/1727-priority-before-staking-rewards-delegators-should-be-able-to-vote-on-protocol-dashboard-dont-hide-button-also-on-dashboard-chang
There were contract changes that allow for users with `active stake` to create and vote on proposals which should be reflected in the dashboard. 
The contract [internal method](https://github.com/AudiusProject/audius-protocol/blob/master/eth-contracts/contracts/Governance.sol#L1094) for calculating active stake was replicated in the protocol dashboard. 
The dashboard show display active amounts (amount - pending decreases) instead of the current amount.
* Allow users with active stake to create gov. proposals
* Allow users with active stake to vote on gov. proposals
* Update the top addresses table to show `active …
> Use active stake

- package.json
- src/components/Timeline/TimelineEvent.module.css
- src/components/Timeline/TimelineEvent.tsx
- src/services/Audius/delegate.ts
- src/services/Audius/serviceProviderClient.ts
- src/store/cache/timeline/hooks.ts
Playing fast and loose with the types here, this definitely needs cleanup.
New events:
- Service Registration + Deregistration
- SP Increase/decrease request/decrease stake 
Not yet handled:
- Delegators requesting/evaluating/cancelling decrease stake (we do handle increase)
- SP decrease cancel stake event
> Handle more events

- src/components/TopAddressesTable/TopAddressesTable.tsx
- src/store/cache/user/hooks.ts
- src/types.ts
Add delegators to the top addresses by voting weight table
Note: I moved the vote history from the service operators to user because delegator users that are not service operators can now vote. 
Note: The fetchUsers method should take a good amount more time now because it has to fetch all delegators for all service operators.
Note: We should eventually normalize the cache be/ we now store delegator in the cache users and in the nested cache users's delegators array which should now just be a reference to the user in the cache.
> Add delegators to top addresses

- package-lock.json
- package.json
- src/services/Audius/claim.ts
- src/store/cache/timeline/hooks.ts
Update the claim event in the timeline to use the get claimed processes event because there is a bug with the get claim event. 
NOTE: Needs changes from libs - https://github.com/AudiusProject/audius-protocol/pull/1132
> Update claim event

- src/App.tsx
- src/components/TopAddressesTable/TopAddressesTable.tsx
- src/components/TopOperatorsTable/TopOperatorsTable.module.css
- src/components/TopOperatorsTable/TopOperatorsTable.tsx
- src/components/TopOperatorsTable/index.tsx
- src/components/TotalStakedStat/TotalStakedStat.tsx
- src/containers/ServiceUsers/ServiceUsers.tsx
- src/containers/ServiceUsers/index.tsx
- src/containers/Services/Services.tsx
- src/store/cache/user/hooks.ts
- src/utils/activeStake.ts
- src/utils/routes.ts
Adds a new components called `Top Operators Table` which is a table of the top service operators
This is the very similar to the `Top Addresses Table`.
The operators table is displayed on the services page and only have the columns for wallet and stake. The stake column is computed as active stake plus total delegated to that service. 
The Top Addresses Table is displayed on the home page and the stake column displays the active stake.
This also make a new page to view all the top addresses at this route `/services/users`
> Add table and page for top users vs top operators

- src/components/TotalStakedStat/TotalStakedStat.tsx
We only set status when we've fetched all users. We need to revisit this and clean it up.
Note: this is currently on prod.
> Fix active stake component logic

- src/components/TopAddressesTable/TopAddressesTable.tsx
- src/components/TopOperatorsTable/TopOperatorsTable.tsx
The rank in the tables were set before sorting the items in the table leading to incorrect rank. 
Closes AUD-128
> Fix rank in tables

- src/components/TopAddressesTable/TopAddressesTable.tsx
Fixes the `vote weight` column in the Top Addresses by Voting Weight table. 
If there is a limit, the `totalVotingPowerStake` the user's stake was divided by to get the percentage was incorrect. 
Closes AUD-125
> Fix vote weight column in top addr table

- package-lock.json
- package.json
- src/components/DelegatesModal/DelegatesModal.tsx
- src/components/DelegatorsModal/DelegatorsModal.tsx
When closing a modal by pushing a new route which un-mounts it, the scroll lock `overflow:hidden` is left on the body of the html, preventing the user from scrolling. There was an issue in the stems modal component which is fixed in this version patch. 
The modal is also left open if close is not called and you navigate back to the page.  
Closes AUD-132
> Fix dashboard scroll lock

- src/store/cache/user/graph/hooks.ts
- src/store/cache/user/hooks.ts
What happens if you perform a tx action to update your stake/delegation is that the code to perform that action waits for metamask tx confirmation and manually updates the user in the cache, but the use of the graph in `useUser` fetches the user every time from the graph and sets it in the store. Because it doesn't have the updated values, old values were shown. 
The solution is to not fetch from the graph if the user is already in the store.
Closes AUD-174
> Don't use cached user from graphql

- package.json
- src/App.tsx
- src/components/Header/Header.tsx
- src/components/Nav/Nav.tsx
- src/hooks/useRerouteLegacy.ts
Updated the protocol dashboard to use hash routing.
Re-routes the old url to the one, ie `/services/users` => `/#/services/users`
Updates the nav component to use hash routing to highlight the right page.
> Hash Routing

- .circleci/config.yml
- package-lock.json
- package.json
- scripts/rerouteLegacy.js
- scripts/updateBuild.js
* Adds a script to query GA to update the build folder and pin files to IPFS
* Adds a script to generate redirect pages for when the dapp is hosted on ipfs
* Updates CI
* Creates a build.zip folder
* Runs script to notify GA to update and pin build in ipfs
* Updates record w/ new CID given from GA
NOTE: I tested this on the stage build end to end, not but on prod
NOTE: I modified the aws permissions for the circleci user to have route53 access
> Add CI for updating the protocol dashboard on IPFS

- package-lock.json
- package.json
- src/components/ProposalHero/ProposalHero.module.css
- src/components/ProposalHero/ProposalHero.tsx
- src/services/Audius/governance/governance.ts
- src/store/cache/proposals/hooks.ts
- src/types.ts
* Update libs to get quorum function from gov. 
* Add binding to audius service
* Update Proposal type to have quorum amount
* Display in Proposal UI
Note: the added quorum met/not met and voted/quorum ui are only displayed if the proposal is active
> Add quorum to proposal

- src/App.module.css
- src/components/RewardStat/RewardStat.module.css
- src/containers/Home/Home.module.css
Fix overflow for mobile yield by adding wrapping.
> Fix mobile yield

- src/components/Proposal/Proposal.tsx
- src/components/ProposalHero/ProposalHero.module.css
- src/components/ProposalHero/ProposalHero.tsx
- src/components/ProposalStatusBadge/ProposalStatusBadge.module.css
- src/components/ProposalStatusBadge/ProposalStatusBadge.tsx
- src/components/ProposalStatusChip/ProposalStatusChip.tsx
- src/services/Audius/governance/governance.ts
- src/store/actions/executeProposal.ts
- src/store/cache/proposals/hooks.ts
- src/store/cache/proposals/slice.ts
- src/types.ts
My attempt and fixing the Governance voting states and adding an execute button I did yesterday in case we needed to fast track this. Currently what happens in the UI is it only shows you the the submit vote buttons, regardless of whether the proposal is in the voting period, execution delay or is awaiting execution. So not only is there not Execute Proposal button but it still shows you the ability to vote, even after the voting period has passed.
I added substates to "In Progress" so the interface can distinguish these actions and they behave in the following ways:
When voting is allowed, show the voting buttons
After voting has ended but before execution, disable the buttons
After execution is allowed, show the Execute Proposal button
What's left to be done?
Execute Proposal button …
> Add execute governance proposal button and fix voting states

- src/components/Button/Button.module.css
- src/components/Delegate/Delegate.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/UserInfo/UserInfo.tsx
- src/containers/User/User.tsx
- src/store/cache/user/graph/formatter.ts
* Fetch the serviceProviderDetails from on chain to get the validBounds field - it is not indexed from the graph
* Disables the claim btn if the user is out of bounds and adds a tooltip
* Fix the Tooltip component isDisabled field was used incorrectly. 
* Fix btn disabled styles
> Add validBounds and disable claims if out of bounds

- .env.prod
- src/App.tsx
- src/components/ErrorModal/ErrorModal.tsx
- src/hooks/useTotalStaked.ts
- src/services/AudiusSubgraph/index.ts
- src/store/api/hooks.ts
- src/store/api/slice.ts
- src/store/cache/user/graph/hooks.ts
- src/store/cache/user/graph/queries.ts
- src/store/index.ts
- src/store/types.ts
- src/utils/fetch.ts
* Update the prod env `REACT_APP_GQL_URI` to point at the graph mainnet gateway
* Add env var `REACT_APP_GQL_BACKUP_URI` to be used on the primary failing
* Add logic for switching graphql uri on primary failure
* Adds slice to hold state for backup available and failure
* Adds logic to switch apollo client provider on failure
* wraps `useQuery` to watch for failures
* Add logic to `useUser` and `useUsers` to try both graphql gateways before falling back to eth contract reads
* Updates `useUser` and `useUsers` graphql queries to get first 200 - fixes estimates for rewards
* NOTE: This should later be changed to actually paginate 🙃
> Migrate the graph endpoint mainnet

- src/components/UserInfo/UserInfo.tsx
Four test cases:
Delegator limit reached
Delegator limit not reached
Delegator limit reached, but already delegated
Regular user (no delegate option)
> Disable delegate btn when delegators has reached limit

- .circleci/config.yml
- package.json
Bump CI resource size to large
Bump script build size to 8GB
* This now matches the audius-client build
> Bump resource size

- src/store/cache/user/graph/formatter.ts
- src/store/cache/user/hooks.ts
Things were not working here because spMinDelegationAmount is always defined, when it is unset, the value is 0, so instead we should check for *no value*.
Tested:
- checked SP page without min set
- checked SP page with min set
> Fix spMinDelegation logic check

- src/services/Audius/AudiusClient.ts
- src/services/Audius/helpers.ts
- src/store/cache/contentNode/hooks.ts
- src/store/cache/discoveryProvider/hooks.ts
Update the fetch node metadata to only fetch location instead of entirety of health check
Falls back to legacy method of fetching location with health check
Discovery Node changes for endpoint ref: https://github.com/AudiusProject/audius-protocol/pull/3101
Tested running against new discovery changes with endpoint and legacy against prod and it worked!
Closes PLAT-138
> Update fetch metadata to only get location and version

- src/components/VerticalBarChart/VerticalBarChart.tsx
- src/store/cache/analytics/hooks.ts
- src/store/cache/music/hooks.ts
- src/store/cache/protocol/hooks.ts
* Removes unnecessary console.logs
* Fixes `fetchEthBlockNumber`
* The problem with this is that it was calling in a setInterval and not called initially, so the client would have to wait 10 seconds before the eth block number was set. Thus, causing an analytics chart to not load. 
* Additionally, because it only updated if the window is active, if it was in view but not active then the chart would never load and looks like a bug
* Removes the hook `const { nodes } = useDiscoveryProviders({})` in the analytics and fetch top tracks/playlists/albums/genres/apps/apis etc. because we only fetch from a single discovery node using libs. it's replaced with `await aud.awaitSetup()` to ensure libs is setup and a discovery node is selected before making the request. 
Fixes PLAT-137
> Remove wait for all nodes on analytics

- .circleci/config.yml
Fixes failing `deploy-staging` CI job, which is caused by changing to the next-gen CircleCI image ([this one-liner](https://github.com/AudiusProject/protocol-dashboard/pull/152/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R83)). See https://circleci.com/docs/next-gen-migration-guide/#troubleshooting.
> Hotfix CI img install

- index.html
- vite.config.ts
Stage deploy worked with Armada, but on prod the IPFS link is unable to serve the files because it's in a relative path (ie, `/ipfs/<cid>`). `npm run start:prod` works, along with `npm run build:prod && npm run serve`.
> Use relative paths for IPFS
